language: ruby
rvm:
  - 2.5.1
cache:
  directories:
    - vendor/bundle
    - node_modules
sudo: false
git:
  depth: 10
before_install:
  - gem install bundler --no-doc
  - nvm install 7
  - nvm use 7
script:
  - npm install
  - script/cibuild
addons:
  apt:
    packages:
      - libcurl3-dev
